### ISSUE TITLE
No longer on npm?

### ISSUE THREAD

**Issue by yocontra** [tj/should.js#103]
```
Don-Juan-PC:protosock contra$ npm install should
npm http GET https://registry.npmjs.org/should
npm http 401 https://registry.npmjs.org/should
npm http GET https://registry.npmjs.org/should
npm http 401 https://registry.npmjs.org/should
npm ERR! Error: unauthorized Name or password is incorrect.: should
npm ERR!     at RegClient.<anonymous> (/usr/local/Cellar/node/0.8.21/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
npm ERR!     at Request.init.self.callback (/usr/local/Cellar/node/0.8.21/lib/node_modules/npm/node_modules/request/main.js:120:22)
npm ERR!     at Request.EventEmitter.emit (events.js:99:17)
npm ERR!     at Request.<anonymous> (/usr/local/Cellar/node/0.8.21/lib/node_modules/npm/node_modules/request/main.js:648:16)
npm ERR!     at Request.EventEmitter.emit (events.js:126:20)
npm ERR!     at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/usr/local/Cellar/node/0.8.21/lib/node_modules/npm/node_modules/request/main.js:610:14)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:126:20)
npm ERR!     at IncomingMessage._emitEnd (http.js:366:10)
npm ERR!     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
npm ERR!     at CleartextStream.socketOnData (http.js:1485:20)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.2.1
npm ERR! command "/usr/local/Cellar/node/0.8.21/bin/node" "/usr/local/bin/npm" "install" "should"
npm ERR! cwd /Users/contra/Projects/protosock
npm ERR! node -v v0.8.21
npm ERR! npm -v 1.2.11
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/contra/Projects/protosock/npm-debug.log
npm ERR! not ok code 0

```

**Comment by tj** [comment]
works for me
