### ISSUE TITLE
using type

### ISSUE THREAD

**Issue by rm-rf-etc** [tj/should.js#136]
The following fails for me, using mocha.

var should = require('should')

describe('using type', function(){
    it('should work', function(){
        'my string'.should.have.type('string')
    })
})

  0 passing (4ms)
  1 failing

  1) using type should work:
     TypeError: Object #<Object> has no method 'typeof'
      at Context.<anonymous> (/Users/MyName/www/rapid/vessel/test/test2.js:6:33)
      at Test.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:211:32)
      at Runner.runTest (/usr/local/lib/node_modules/mocha/lib/runner.js:358:10)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:404:12
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:284:14)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:293:7
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:237:23)
      at Object._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:261:5)
      at processImmediate [as _immediateCallback](timers.js:330:15)

**Comment by rm-rf-etc** [comment]
while this works fine:

var should = require('should')

describe('using type', function(){
    it('should work', function(){
        (typeof 'my string' === 'string').should.have.true
    })
})

  ․

  1 passing (3ms)

**Comment by btd** [comment]
Current docs for version 2.0.0 which is not published now to npmjs. It will be published i hope at this week.
For version 1.x.x use this [readme](https://github.com/visionmedia/should.js/blob/1.3.0/Readme.md).
