### ISSUE TITLE
equals() fails for multidimensional arrays

### ISSUE THREAD

**Issue by macalinao** [tj/should.js#72]
``` coffeescript
[[1, 2, 3], [4, 5, 6]].should.equal [[1, 2, 3], [4, 5, 6]]
```

This fails.

```

     AssertionError: expected [ [ 1, 2, 3 ], [ 4, 5, 6 ] ] to equal [ [ 1, 2, 3 ], [ 4, 5, 6 ] ]
      at Object.equal (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/should/lib/should.js:303:10)
      at Context.<anonymous> (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/test/utils_test.coffee:12:46)
      at Test.run (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/mocha/lib/runnable.js:168:32)
      at Runner.runTest (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/mocha/lib/runner.js:295:10)
      at /Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/mocha/lib/runner.js:339:12
      at next (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/mocha/lib/runner.js:223:14)
      at /Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/mocha/lib/runner.js:232:7
      at next (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/mocha/lib/runner.js:182:23)
      at Array.0 (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/mocha/lib/runner.js:200:5)
      at EventEmitter._tickCallback (node.js:192:40)
```

**Comment by macalinao** [comment]
Never mind, this seems to be an underlying problem with Javascript. I'm just comparing the strings for now.

**Comment by enyo** [comment]
`.equal` is a strict equal. And `[] !== []`. That's why it fails. Two newly created arrays aren't the same. AFAIK `.eql()` should work though.

**Comment by tj** [comment]
yup `.eql()` is for "lose equality", bit of a rubyism naming-wise
